spring.application.name = TechTales

spring.datasource.url = ${DB_URL}
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}

spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view = false

app.jwt.secret = 4f3f4a76099689f98f5bc0fd5b54fcb447f8e35f4ae129afd244967ccb2fc043
app.jwt.expiration-ms = 86400000
